### ISSUE TITLE
Docker container loses authentication after a little less than 24 hours or so

### ISSUE THREAD

**Issue by claflico** [Prouser123/xbl-web-api#9]
I'm experimenting with the docker image of this as I would like to possibly incorporate it in an API for use by a Minecraft Bedrock Edition docker image. At around the 24hr mark of uptime it quits responding to anything but the homepage and it shows that authentication is false.

This is the only thing I see in the logs:

Hello 60s!
Hello 60s!
Hello 60s!
Hello 60s!
Hello 60s!
Hello 60s!
Hello 60s!
Hello 60s!
Adding cache headers...
Hello 60s!
Adding cache headers...

Other than restarting the container is there something that's supposed to re-authenticate it?

Thank you

**Comment by jcxldn** [comment]
Hello @claflico!

First of all I'd like to apologize for my *very* late reply.

Currently, the automatic re-authentication does not run correctly so yes, on it's own it will lose authentication after around 24 hours. 

I'm currently in the process of re-writing the whole service be asynchronous and use a newer library version, which will fix #7. As part of the rewrite to become async, I've swapped the http server to Quart, and this issue is fixed in the rewrite.

I'm currently re-implementing all the routes in the rewritten server, and I hope to have it ready to go soon! I'll make a draft pull request so it's easier for everyone to track what's going on with it.

Thanks!

-James

**Comment by jcxldn** [comment]
Hi again!

#10 has now been merged and is now live. Authentication tokens are now checked once a minute and refreshed if necessary.

I'll monitor the instance for the next few days to see if this is fixed.

Thanks!

-James
